import { createContext, useContext, useState, useCallback, ReactNode } from "react";

export type Lang = "en" | "bm";

interface LanguageContextType {
  lang: Lang;
  toggleLang: () => void;
  t: (key: string) => string;
}

const translations: Record<string, Record<Lang, string>> = {
  // ── Header ─────────────────────────────────────────────────────────────────
  "header.title":    { en: "Malaysia Labour Market", bm: "Pasaran Buruh Malaysia" },
  "header.subtitle": { en: "Employment Dashboard",   bm: "Papan Pemuka Pekerjaan" },
  "nav.snapshot":    { en: "Snapshot",        bm: "Gambaran"               },
  "nav.trends":      { en: "Trends",          bm: "Trend"                  },
  "nav.sectors":     { en: "Sectors",         bm: "Sektor"                 },
  "nav.underemployment": { en: "Underemployment", bm: "Kerja Bawah Kelayakan" },
  "nav.states":      { en: "States",          bm: "Negeri"                 },

  // ── Hero ───────────────────────────────────────────────────────────────────
  "hero.badge":  { en: "Official DOSM Data · Updated Monthly",
                   bm: "Data Rasmi DOSM · Dikemaskini Setiap Bulan" },
  "hero.title1": { en: "Malaysia's Jobs.",    bm: "Pekerjaan Malaysia."   },
  "hero.title2": { en: "By the Numbers.",     bm: "Dalam Angka."          },
  "hero.desc":   { en: "Sector shifts, state comparisons and skills insights. Malaysia's labour market, decoded for everyone.",
                   bm: "Perubahan sektor, perbandingan antara negeri dan pandangan kemahiran. Pasaran buruh Malaysia, dihuraikan untuk semua orang." },

  // ── News ───────────────────────────────────────────────────────────────────
  "news.title":    { en: "Labour Market Pulse",   bm: "Denyutan Pasaran Buruh"  },
  "news.subtitle": { en: "Google News · Malaysian sources · past 3 days",
                     bm: "Google News · Sumber Malaysia · 3 hari lepas"         },
  "news.bm25":     { en: "BM25",                  bm: "BM25"                    },
  "news.howTitle": { en: "How news is filtered",  bm: "Bagaimana berita ditapis"},
  "news.howP1en":  { en: "Articles are fetched from Google News (Malaysian sources, past 3 days) and scored using BM25 against 8 labour market topics.",
                     bm: "Artikel diambil dari Google News (sumber Malaysia, 3 hari lepas) dan dinilai menggunakan BM25 berdasarkan 8 topik pasaran buruh." },
  "news.howP2":    { en: "BM25 understands context: term frequency saturation, IDF weighting for rare terms (EPF, HRDC), and document length normalisation.",
                     bm: "BM25 memahami konteks: ketepuan frekuensi terma, pemberat IDF untuk terma jarang (KWSP, HRDC), dan penormalan panjang dokumen." },
  "news.howP3":    { en: "All scoring happens on Netlify's servers. Zero ML downloads, zero memory pressure.",
                     bm: "Semua penilaian dijalankan di pelayan Netlify. Tiada muat turun ML, tiada beban memori." },
  "news.howFooter":{ en: "Topics: Wages, Hiring, Skills, Policy, Gig, Migrant Labour, Industry, Economy.",
                     bm: "Topik: Gaji, Pengambilan Kerja, Kemahiran, Dasar, Gig, Pekerja Asing, Industri, Ekonomi." },
  "news.footer":   { en: "BM25 scored server-side · Google News MY · past 3 days · cached 10 min",
                     bm: "BM25 dinilai di pelayan · Google News MY · 3 hari lepas · cache 10 minit"  },
  "news.howLink":  { en: "How this works",        bm: "Bagaimana ia berfungsi"  },
  "news.empty":    { en: "No relevant labour market news right now.",
                     bm: "Tiada berita pasaran buruh yang berkaitan buat masa ini." },
  "news.retry":    { en: "Refresh",               bm: "Muat Semula"             },
  "news.error":    { en: "Could not load news.",  bm: "Gagal memuatkan berita." },
  "news.positive": { en: "Positive",  bm: "Positif" },
  "news.negative": { en: "Negative",  bm: "Negatif" },
  "news.neutral":  { en: "Neutral",   bm: "Neutral" },

  // ── Section headers ────────────────────────────────────────────────────────
  "section.insights":       { en: "Market News",
                              bm: "Berita Pasaran" },
  "section.kpi":            { en: "Key Labour Market Snapshot",
                              bm: "Gambaran Utama Pasaran Buruh" },
  "section.trends":         { en: "Is the job market improving or worsening?",
                              bm: "Adakah pasaran kerja semakin baik atau semakin buruk?" },
  "section.sectors":        { en: "Where are the job opportunities?",
                              bm: "Di mana peluang pekerjaan?" },
  "section.occupations":    { en: "Which occupations are most critical in Malaysia?",
                              bm: "Pekerjaan apa paling kritikal di Malaysia?" },
  "section.underemployment":{ en: "Are graduates working in the right jobs?",
                              bm: "Adakah graduan bekerja dalam bidang yang sesuai?" },
  "section.states":         { en: "How does your state compare?",
                              bm: "Bagaimana keadaan negeri anda berbanding negeri lain?" },
  "section.regional":       { en: "Which state offers the best opportunities?",
                              bm: "Negeri mana menawarkan peluang terbaik?" },
  "section.jobhealth":      { en: "How good is the job market for you?",
                              bm: "Sebaik mana pasaran kerja untuk anda?" },
  "section.wages":          { en: "What do different industries pay?",
                              bm: "Berapa bayaran gaji oleh industri yang berbeza?" },

  // ── Footer ─────────────────────────────────────────────────────────────────
  "footer.text":    { en: "Data sourced from",  bm: "Sumber data daripada"     },
  "footer.updated": { en: "Updated monthly",    bm: "Dikemaskini setiap bulan" },
  "footer.built":   { en: "Built for Malaysia", bm: "Dibina untuk Malaysia"    },

  // ── Labour Health Score ───────────────────────────────────────────────────
  "health.title":   { en: "Labour Health Index", bm: "Indeks Kesihatan Buruh" },
  "health.outOf":   { en: "out of 100",           bm: "daripada 100"           },
  "health.strong":     { en: "Strong",     bm: "Kukuh"        },
  "health.healthy":    { en: "Healthy",    bm: "Sihat"        },
  "health.recovering": { en: "Recovering", bm: "Sedang Pulih" },
  "health.weak":       { en: "Weak",       bm: "Lemah"        },
  "health.strong.desc":     { en: "Exceptionally low unemployment and strong workforce participation.",
                              bm: "Kadar pengangguran sangat rendah dan penyertaan tenaga kerja yang kukuh." },
  "health.healthy.desc":    { en: "Solid labour market with steady employment growth.",
                              bm: "Pasaran buruh yang kukuh dengan pertumbuhan pekerjaan yang stabil." },
  "health.recovering.desc": { en: "Gradual improvements across key labour indicators.",
                              bm: "Penambahbaikan beransur-ansur dalam petunjuk buruh utama." },
  "health.weak.desc":       { en: "Labour market facing elevated unemployment or low participation.",
                              bm: "Pasaran buruh menghadapi kadar pengangguran tinggi atau penyertaan yang rendah." },

  // ── Data Insight Cards ────────────────────────────────────────────────────
  "insight.didYouKnow": { en: "DID YOU KNOW?",          bm: "TAHUKAH ANDA?"            },
  "insight.trend":      { en: "INTERESTING TREND",      bm: "TREND MENARIK"            },
  "insight.jobMarket":  { en: "JOB MARKET INSIGHT",     bm: "PANDANGAN PASARAN KERJA"  },
  "insight.pandemic":   { en: "PANDEMIC IMPACT",        bm: "KESAN PANDEMIK"           },
  "insight.highest":    { en: "recorded the highest unemployment at",
                          bm: "mencatat pengangguran tertinggi pada" },
  "insight.lowest":     { en: "has the lowest at",      bm: "mencatat paling rendah pada" },
  "insight.lfpr":       { en: "Malaysia's LFPR reached its highest level of",
                          bm: "Kadar Penyertaan Tenaga Buruh Malaysia mencapai paras tertinggi pada" },
  "insight.lfpr2":      { en: "showing more people entering the workforce than ever.",
                          bm: "menunjukkan lebih ramai rakyat menyertai tenaga kerja berbanding sebelum ini." },
  "insight.growth":     { en: "Employment has grown by",    bm: "Pekerjaan telah berkembang sebanyak" },
  "insight.since":      { en: "since the first recorded month, expanding from",
                          bm: "sejak bulan pertama direkodkan, meningkat daripada" },
  "insight.to":         { en: "to",       bm: "kepada"   },
  "insight.workers":    { en: "workers.", bm: "pekerja." },
  "insight.peaked":     { en: "Unemployment peaked at",  bm: "Pengangguran memuncak pada" },
  "insight.in":         { en: "in",       bm: "pada"     },
  "insight.pandemic2":  { en: "during the pandemic, but has since recovered to",
                          bm: "ketika pandemik, tetapi sejak itu telah pulih kepada" },
  "insight.asOf":       { en: "as of",    bm: "setakat"  },

  // ── KPI Cards ─────────────────────────────────────────────────────────────
  "kpi.employmentRate":    { en: "Employment Rate",       bm: "Kadar Pekerjaan"           },
  "kpi.unemploymentRate":  { en: "Unemployment Rate",     bm: "Kadar Pengangguran"        },
  "kpi.labourParticipation": { en: "Labour Participation", bm: "Penyertaan Tenaga Kerja"  },
  "kpi.skillsMismatch":    { en: "Skills Mismatch",       bm: "Ketidakpadanan Kemahiran"  },
  "kpi.latestData":        { en: "Latest data",           bm: "Data terkini"              },
  "kpi.tooltip.employment":   { en: "Percentage of labour force currently employed.",
                                bm: "Peratus tenaga kerja yang sedang bekerja." },
  "kpi.tooltip.unemployment": { en: "Percentage actively seeking but unable to find work. Lower is better.",
                                bm: "Peratus rakyat yang aktif mencari kerja tetapi belum berjaya. Lebih rendah lebih baik." },
  "kpi.tooltip.participation":{ en: "Percentage of working-age population in the labour force.",
                                bm: "Peratus penduduk berumur bekerja yang berada dalam tenaga kerja." },
  "kpi.tooltip.mismatch":     { en: "Tertiary-educated workers in jobs below their qualification level.",
                                bm: "Pekerja berkelulusan tinggi yang bekerja di bawah tahap kelayakan mereka." },

  // ── Trend Charts ──────────────────────────────────────────────────────────
  "trends.title":          { en: "Employment Trends",       bm: "Trend Pekerjaan"            },
  "trends.monthly":        { en: "Monthly data from",       bm: "Data bulanan sejak"         },
  "trends.allYears":       { en: "All Years",               bm: "Semua Tahun"                },
  "trends.unemployment":   { en: "Unemployment",            bm: "Pengangguran"               },
  "trends.workforce":      { en: "Workforce",               bm: "Tenaga Kerja"               },
  "trends.participation":  { en: "Participation",           bm: "Penyertaan"                 },
  "trends.jobChange":      { en: "Job Change",              bm: "Perubahan Pekerjaan"        },
  "trends.preCovid":       { en: "Pre-COVID avg (3.3%)",    bm: "Purata sebelum COVID (3.3%)"},
  "trends.labourForce":    { en: "Labour Force",            bm: "Tenaga Kerja"               },
  "trends.employed":       { en: "Employed",                bm: "Bekerja"                    },
  "trends.unemploymentRate": { en: "Unemployment Rate",     bm: "Kadar Pengangguran"         },
  "trends.participationRate":{ en: "Participation Rate",    bm: "Kadar Penyertaan"           },
  "trends.70target":       { en: "70% target",              bm: "Sasaran 70%"                },
  "trends.note.unemployment":  { en: "The dashed line marks the pre-COVID baseline average of 3.3%",
                                 bm: "Garisan putus-putus menandakan purata sebelum COVID iaitu 3.3%" },
  "trends.note.workforce":     { en: "Gap between Labour Force and Employed lines represents unemployment count",
                                 bm: "Jurang antara garisan Tenaga Kerja dan Bekerja menunjukkan jumlah pengangguran" },
  "trends.note.participation": { en: "Dashed line marks the 70% participation target",
                                 bm: "Garisan putus-putus menandakan sasaran penyertaan 70%" },
  "trends.note.change":        { en: "Month-over-month change in total employed persons (thousands)",
                                 bm: "Perubahan bulan ke bulan dalam jumlah pekerja (ribu)" },

  // ── Sector Chart ──────────────────────────────────────────────────────────
  "sectors.title": { en: "Employment by Sector",
                     bm: "Pekerjaan mengikut Sektor" },
  "sectors.desc":  { en: "How Malaysia's workforce is distributed across the three main economic sectors",
                     bm: "Bagaimana tenaga kerja Malaysia diagihkan dalam tiga sektor ekonomi utama" },
  "sectors.snapshot":         { en: "Snapshot",         bm: "Gambaran"              },
  "sectors.historicalTrend":  { en: "Historical Trend", bm: "Trend Sejarah"         },
  "sectors.structuralShift":  { en: "Structural Shift", bm: "Perubahan Struktur"    },
  "sectors.services":         { en: "Services",         bm: "Perkhidmatan"          },
  "sectors.industry":         { en: "Industry",         bm: "Industri"              },
  "sectors.agriculture":      { en: "Agriculture",      bm: "Pertanian"             },
  "sectors.grew":             { en: "grew",             bm: "berkembang"            },
  "sectors.fell":             { en: "fell",             bm: "menurun"               },
  "sectors.overDecade":       { en: "over the past decade", bm: "sepanjang dekad lalu" },
  "sectors.share":            { en: "share",            bm: "bahagian"              },
  "sectors.declined":         { en: "declined",         bm: "menurun"               },
  "sectors.transformation":   { en: "Malaysia's ongoing structural transformation",
                                bm: "Transformasi struktur Malaysia yang berterusan" },
  "sectors.trendDesc":        { en: "How each sector's share of total employment has evolved since 2005",
                                bm: "Bagaimana bahagian setiap sektor dalam jumlah pekerjaan berubah sejak 2005" },

  // ── InDemand Chart ────────────────────────────────────────────────────────
  "indemand.title":       { en: "In-Demand Industries & Occupations",
                            bm: "Industri & Pekerjaan Dalam Permintaan" },
  "indemand.subtitle":    { en: "Skilled roles in shortage across Malaysia, mapped by sector",
                            bm: "Pekerjaan mahir yang kekurangan tenaga di seluruh Malaysia, dikelaskan mengikut sektor" },
  "indemand.occupation":  { en: "Occupation",       bm: "Pekerjaan"              },
  "indemand.avgSalary":   { en: "Avg Salary (MYR)", bm: "Gaji Purata (MYR)"      },
  "indemand.mascoTitle":  { en: "MASCO category share of nominations",
                            bm: "Bahagian kategori MASCO dalam pekerjaan kritikal" },
  "indemand.of":          { en: "100% of",          bm: "100% daripada"          },
  "indemand.roles":       { en: "roles",             bm: "pekerjaan"              },
  "indemand.skillsLabel": { en: "Skills wanted across all roles",
                            bm: "Kemahiran diperlukan merentasi semua pekerjaan"   },
  "indemand.skillsSource":{ en: "MOHE Graduate Tracer",
                            bm: "Kajian Pengesanan Graduan MOHE"                  },
  "indemand.searchPlaceholder": { en: "Find a role like Software Developer, Pharmacist, Welder...",
                                  bm: "Cari pekerjaan seperti Pembangun Perisian, Ahli Farmasi, Tukang Las..." },
  "indemand.newOnly":     { en: "NEW ONLY",          bm: "BAHARU SAHAJA"          },
  "indemand.reset":       { en: "reset",             bm: "tetapkan semula"        },
  "indemand.noMatchCard": { en: "No matching roles", bm: "Tiada pekerjaan yang sepadan" },
  "indemand.noMatchMsg":  { en: "No roles match",    bm: "Tiada pekerjaan yang sepadan dengan" },
  "indemand.withNewFilter": { en: "with NEW filter", bm: "dengan penapis BAHARU"  },
  "indemand.resetFilters":{ en: "Reset filters",     bm: "Tetapkan semula penapis"},
  "indemand.addedSince":  { en: "added since 2023",  bm: "ditambah sejak 2023"    },
  "indemand.seeChanged":  { en: "see what changed",  bm: "lihat apa yang berubah" },
  "indemand.newInEdition":{ en: "NEW IN",            bm: "BAHARU DALAM"           },
  "indemand.moreRoles":   { en: "more",              bm: "lagi"                   },
  "indemand.export":      { en: "Export",            bm: "Eksport"                },
  "indemand.diffIntro":   { en: "MyCOL grew from",   bm: "MyCOL berkembang daripada" },
  "indemand.diffRolesIn": { en: "roles in 2023 to",  bm: "pekerjaan pada 2023 kepada" },
  "indemand.diffLanded":  { en: "Here's where the new additions landed:",
                            bm: "Inilah di mana penambahan baharu berlaku:"        },
  "indemand.diffNew":     { en: "new",               bm: "baharu"                 },
  "indemand.repNote":     { en: "1,200 Malaysians returned via TalentCorp REP in Q1 2025, mostly into roles on this list. Skills Passport Malaysia: 250,000+ active credential holders.",
                            bm: "1,200 rakyat Malaysia kembali melalui Program REP TalentCorp pada S1 2025, kebanyakannya ke pekerjaan dalam senarai ini. Pasport Kemahiran Malaysia: lebih 250,000 pemegang kelayakan aktif." },
  // Entry route translations (shown under MASCO group in sector cards)
  "indemand.route.manager":      { en: "Bachelor + senior experience",         bm: "Ijazah + pengalaman kanan"            },
  "indemand.route.professional": { en: "Bachelor + professional registration",  bm: "Ijazah + pendaftaran profesional"     },
  "indemand.route.technician":   { en: "Diploma + industry certification",      bm: "Diploma + sijil industri"             },
  "indemand.route.clerical":     { en: "SPM + administrative training",         bm: "SPM + latihan pentadbiran"            },
  "indemand.route.trades":       { en: "SKM Level 3 or apprenticeship",         bm: "SKM Tahap 3 atau perantisan"          },
  "indemand.route.operator":     { en: "SKM Level 1 or on-job training",        bm: "SKM Tahap 1 atau latihan kerja"       },

  // ── Underemployment ───────────────────────────────────────────────────────
  "under.title": { en: "Skills Mismatch & Underemployment",
                   bm: "Ketidakpadanan Kemahiran & Kerja Bawah Kelayakan" },
  "under.desc":  { en: "Tertiary-educated workers in jobs below their qualification level — a key signal of labour market inefficiency",
                   bm: "Pekerja berkelulusan tinggi yang bekerja di bawah tahap kelayakan, satu petunjuk utama ketidakcekapan pasaran buruh" },
  "under.byGender":    { en: "By Gender",     bm: "Mengikut Jantina"              },
  "under.byAge":       { en: "By Age",        bm: "Mengikut Umur"                 },
  "under.overTime":    { en: "Over Time",     bm: "Sepanjang Masa"                },
  "under.currentRate": { en: "Current Rate",  bm: "Kadar Semasa"                  },
  "under.peakRate":    { en: "Peak Rate",     bm: "Kadar Tertinggi"               },
  "under.youthVsSenior": { en: "Youth vs Senior",  bm: "Belia berbanding Warga Emas" },
  "under.mostAffected":  { en: "Most Affected",    bm: "Paling Terjejas"             },
  "under.highestRecorded":{ en: "Highest recorded", bm: "Tertinggi pernah direkodkan" },
  "under.genderDesc":  { en: "Quarterly skills mismatch rate by gender — are women or men more affected?",
                         bm: "Kadar ketidakpadanan kemahiran setiap suku tahun mengikut jantina, adakah wanita atau lelaki lebih terjejas?" },
  "under.ageDesc":     { en: "which age group faces the most skills mismatch?",
                         bm: "kumpulan umur mana yang paling banyak menghadapi ketidakpadanan kemahiran?" },
  "under.trendDesc":   { en: "Overall skills mismatch rate trend — is Malaysia's graduate underemployment improving?",
                         bm: "Trend keseluruhan kadar ketidakpadanan kemahiran, adakah keadaan graduan Malaysia bertambah baik?" },
  "under.youth":      { en: "Youth",        bm: "Belia"              },
  "under.youngAdult": { en: "Young Adult",  bm: "Dewasa Muda"        },
  "under.midCareer":  { en: "Mid Career",   bm: "Pertengahan Kerjaya"},
  "under.senior":     { en: "Senior",       bm: "Warga Emas"         },

  // ── State Map ─────────────────────────────────────────────────────────────
  "state.title":            { en: "State-Level Labour Market", bm: "Pasaran Buruh Peringkat Negeri" },
  "state.unemployment":     { en: "Unemployment",         bm: "Pengangguran"         },
  "state.participation":    { en: "Participation",        bm: "Penyertaan"           },
  "state.avgUnemployment":  { en: "Avg Unemployment",     bm: "Purata Pengangguran"  },
  "state.avgParticipation": { en: "Avg Participation",    bm: "Purata Penyertaan"    },
  "state.bestUnemployment": { en: "Best Unemployment",    bm: "Pengangguran Terbaik" },
  "state.statesTracked":    { en: "States Tracked",       bm: "Negeri Dijejaki"      },
  "state.choropleth":       { en: "Choropleth",           bm: "Peta Kawasan"         },
  "state.clickState":       { en: "Click a state to pin details • Hover to preview",
                              bm: "Klik negeri untuk lihat butiran lengkap, hover untuk pratonton" },
  "state.labourForce":      { en: "Labour Force",         bm: "Tenaga Kerja"         },
  "state.employed":         { en: "Employed",             bm: "Bekerja"              },
  "state.unemployed":       { en: "Unemployed",           bm: "Menganggur"           },
  "state.unemploymentRate": { en: "Unemployment Rate",    bm: "Kadar Pengangguran"   },
  "state.participationRate":{ en: "Participation Rate",   bm: "Kadar Penyertaan"     },
  "state.rankings":         { en: "Rankings",             bm: "Kedudukan"            },
  "state.clickForDetails":  { en: "Click a state on the map for details",
                              bm: "Klik negeri pada peta untuk lihat butiran" },
  "state.close":            { en: "Close",                bm: "Tutup"                },
  "state.vsNational":       { en: "Unemployment vs national avg",
                              bm: "Pengangguran berbanding purata kebangsaan" },
  "state.low":              { en: "Low",    bm: "Rendah" },
  "state.high":             { en: "High",   bm: "Tinggi" },

  // ── Regional / Economic Opportunity ───────────────────────────────────────
  "regional.title": { en: "State Economic Opportunity Index",
                      bm: "Indeks Peluang Ekonomi Negeri" },
  "regional.desc":  { en: "Composite score: household income, unemployment, poverty & equality — live from DOSM",
                      bm: "Skor gabungan: pendapatan isi rumah, pengangguran, kemiskinan & kesaksamaan, terus daripada DOSM" },
  "regional.score":          { en: "Score",               bm: "Skor"                   },
  "regional.income":         { en: "Income",              bm: "Pendapatan"             },
  "regional.unemploy":       { en: "Unemploy.",           bm: "Penganggur."            },
  "regional.poverty":        { en: "Poverty",             bm: "Kemiskinan"             },
  "regional.topStates":      { en: "Top Opportunity States", bm: "Negeri Berpeluang Terbaik" },
  "regional.needsAttention": { en: "Needs Attention",     bm: "Memerlukan Perhatian"   },
  "regional.selectState":    { en: "Select a state",      bm: "Pilih negeri"           },
  "regional.clickBar":       { en: "Click any bar to see full economic profile with radar breakdown",
                               bm: "Klik mana-mana bar untuk lihat profil ekonomi lengkap dengan analisis radar" },
  "regional.highOpp":        { en: "High Opportunity",    bm: "Peluang Tinggi"         },
  "regional.goodOpp":        { en: "Good Opportunity",    bm: "Peluang Baik"           },
  "regional.moderate":       { en: "Moderate",            bm: "Sederhana"              },
  "regional.needsImprovement":{ en: "Needs Improvement",  bm: "Perlu Penambahbaikan"   },
  "regional.challenging":    { en: "Challenging",         bm: "Mencabar"               },
  "regional.loading":        { en: "Loading live data from DOSM...",
                               bm: "Memuatkan data terkini daripada DOSM..."            },
  "regional.clickBarShort":  { en: "Click any bar to see full state profile",
                               bm: "Klik mana-mana bar untuk lihat profil negeri"       },
  "regional.medianIncome":   { en: "Median Income",       bm: "Pendapatan Median"      },
  "regional.meanIncome":     { en: "Mean Income",         bm: "Pendapatan Purata"      },
  "regional.povertyRate":    { en: "Poverty Rate",        bm: "Kadar Kemiskinan"       },
  "regional.giniIndex":      { en: "Gini Index",          bm: "Indeks Gini"            },
  "regional.scoreLabel":     { en: "Score:",              bm: "Skor:"                  },
  "regional.unemploymentDetail": { en: "Unemployment",    bm: "Pengangguran"           },
  "regional.participationDetail":{ en: "Participation",   bm: "Penyertaan"             },
  "regional.barScore":       { en: "Opportunity Score by State",  bm: "Skor Peluang mengikut Negeri"              },
  "regional.barIncome":      { en: "Median Monthly Household Income (RM)", bm: "Pendapatan Isi Rumah Bulanan Median (RM)" },
  "regional.barUrate":       { en: "Unemployment Rate (%) — lower is better",  bm: "Kadar Pengangguran (%), lebih rendah lebih baik"  },
  "regional.barPoverty":     { en: "Poverty Incidence (%) — lower is better",  bm: "Insiden Kemiskinan (%), lebih rendah lebih baik"  },
  "regional.tooltipScore":   { en: "Score",         bm: "Skor"               },
  "regional.tooltipMedian":  { en: "Median Income", bm: "Pendapatan Median"  },
  "regional.tooltipUnemp":   { en: "Unemployment",  bm: "Pengangguran"       },
  "regional.tooltipPoverty": { en: "Poverty Rate",  bm: "Kadar Kemiskinan"   },

  // ── Job Market Health ─────────────────────────────────────────────────────
  "job.title":        { en: "Check Your Job Market Health",
                        bm: "Semak Kesihatan Pasaran Kerja Anda" },
  "job.personalised": { en: "Personalised Analysis",    bm: "Analisis Peribadi"          },
  "job.desc":         { en: "Select a location and industry to see a personalised labour health score.",
                        bm: "Pilih lokasi dan industri untuk lihat skor kesihatan buruh khusus untuk anda." },
  "job.selectState":  { en: "Select state",             bm: "Pilih negeri"               },
  "job.selectIndustry":{ en: "Select industry",         bm: "Pilih industri"             },
  "job.analyze":      { en: "Analyze Job Market",       bm: "Analisis Pasaran Kerja"     },
  "job.analysing":    { en: "Analysing…",               bm: "Sedang menganalisis…"       },
  "job.emptyState":   { en: "Select a location and industry to analyze the job market.",
                        bm: "Pilih lokasi dan industri untuk analisis pasaran kerja." },
  "job.emptySubtitle":{ en: "7 indicators · personalised insight · MyCOL critical roles",
                        bm: "7 petunjuk · pandangan peribadi · pekerjaan kritikal MyCOL" },
  "job.analyzingMarket": { en: "Analyzing labour market…",
                           bm: "Sedang menganalisis pasaran buruh…"                      },
  "job.analyzingSubtitle": { en: "Calculating 7 indicators and matching MyCOL roles...",
                             bm: "Mengira 7 petunjuk dan memadankan pekerjaan kritikal MyCOL..." },
  "job.unemployment": { en: "Unemployment",             bm: "Pengangguran"               },
  "job.participation":{ en: "Participation",            bm: "Penyertaan"                 },
  "job.growth":       { en: "Growth",                   bm: "Pertumbuhan"                },
  "job.insight":      { en: "Insight",                  bm: "Pandangan"                  },
  "job.trendTitle":   { en: "Unemployment Trend",       bm: "Trend Pengangguran"         },
  "job.suggestions":  { en: "Suggestions for You",      bm: "Cadangan Untuk Anda"        },
  // Tabs
  "job.tabAll":       { en: "All Indicators",           bm: "Semua Petunjuk"             },
  "job.tabRadar":     { en: "Radar View",               bm: "Paparan Radar"              },
  "job.tabTrend":     { en: "Trend",                    bm: "Trend"                      },
  // Buttons
  "job.close":        { en: "Close",                    bm: "Tutup"                      },
  "job.pdfReport":    { en: "PDF Report",               bm: "Laporan PDF"                },
  // Score labels
  "job.labourMarket": { en: "Labour Market",            bm: "Pasaran Buruh"              },
  "job.outOf":        { en: "out of 100",               bm: "daripada 100"               },
  // Indicators (reuse kpi keys where possible; these are for unique ones)
  "job.ind.unemploymentRate":  { en: "Unemployment Rate",    bm: "Kadar Pengangguran"         },
  "job.ind.participationRate": { en: "Participation Rate",   bm: "Kadar Penyertaan"           },
  "job.ind.empGrowth":         { en: "Employment Growth",    bm: "Pertumbuhan Pekerjaan"      },
  "job.ind.youthUnemp":        { en: "Youth Unemployment",   bm: "Pengangguran Belia"         },
  "job.ind.skillsMismatch":    { en: "Skills Mismatch",      bm: "Ketidakpadanan Kemahiran"   },
  "job.ind.wageNational":      { en: "Wage vs National",     bm: "Gaji berbanding Kebangsaan" },
  "job.ind.jobStability":      { en: "Job Stability",        bm: "Kestabilan Pekerjaan"       },
  // Indicator detail labels
  "job.ind.vsNational":        { en: "vs national",          bm: "berbanding kebangsaan"      },
  "job.ind.monthOnMonth":      { en: "month-on-month",       bm: "bulan ke bulan"             },
  "job.ind.ages1524":          { en: "ages 15 to 24",        bm: "umur 15 hingga 24"          },
  "job.ind.gradsWrongJobs":    { en: "graduates in wrong jobs", bm: "graduan dalam kerja tak sepadan" },
  "job.ind.nationalMedian":    { en: "national median",      bm: "median kebangsaan"          },
  "job.ind.lowTurnover":       { en: "low turnover & duration risk", bm: "pusing ganti rendah & risiko tempoh" },
  // Trend chart labels
  "job.thisSectorState":  { en: "This sector/state",         bm: "Sektor/negeri ini"          },
  "job.national":         { en: "National",                  bm: "Kebangsaan"                 },
  "job.trendNote":        { en: "Estimated unemployment trend,", bm: "Anggaran trend pengangguran," },
  "job.vsNationalAvg":    { en: "vs national average (last 12 months)", bm: "berbanding purata kebangsaan (12 bulan lepas)" },
  // Skills section
  "job.inDemandSkills":   { en: "In-Demand Skills for",      bm: "Kemahiran Dalam Permintaan untuk" },
  // Critical roles section
  "job.criticalTitle":    { en: "Critical Roles to Target in",
                            bm: "Pekerjaan Kritikal untuk Dicapai dalam"  },
  "job.criticalDesc":     { en: "Roles that TalentCorp & ILMIA officially flag as having persistent skills shortages. Shortage status means stronger demand and salary leverage.",
                            bm: "Pekerjaan yang TalentCorp & ILMIA tandakan secara rasmi sebagai kekurangan kemahiran berterusan. Status kekurangan bermakna permintaan lebih tinggi dan leverage gaji lebih kukuh." },
  "job.criticalClusters": { en: "Mapped from MyCOL clusters",
                            bm: "Dipetakan daripada kluster MyCOL"        },
  "job.moreCritical":     { en: "more roles",                bm: "pekerjaan lagi"             },
  // Source line
  "job.sourceNote":       { en: "Analysis uses live DOSM data and TalentCorp MyCOL",
                            bm: "Analisis menggunakan data DOSM terkini dan MyCOL TalentCorp"  },
  "job.indicative":       { en: "Indicative only",           bm: "Anggaran sahaja"            },
  // Dynamic insight & suggestion helpers
  "job.insightSectorIn":      { en: "sector in",             bm: "sektor di"                  },
  "job.insightShows":         { en: "shows",                 bm: "menunjukkan"                },
  "job.insightConditions":    { en: "labour market conditions, with an adjusted unemployment rate of",
                                bm: "keadaan pasaran buruh, dengan kadar pengangguran terlaras sebanyak" },
  "job.insightParticipation": { en: "and participation at",  bm: "dan penyertaan pada"        },
  "job.insightDrivenBy":      { en: "This is driven by",     bm: "Ini didorong oleh"          },
  "job.suggestConsider":      { en: "Consider",              bm: "Pertimbangkan"              },
  "job.suggestStrongestIn":   { en: ", strongest growth trend in",
                                bm: ", trend pertumbuhan paling kukuh di"                     },
  "job.suggestScoreLabel":    { en: "score",                 bm: "skor"                       },
  "job.suggestSlowerIn":      { en: "shows slower recovery in",
                                bm: "menunjukkan pemulihan lebih perlahan di"                  },
  "job.suggestStable":        { en: "sector has stable employment rates",
                                bm: "sektor mempunyai kadar pekerjaan yang stabil"             },

  // ── Story Mode ────────────────────────────────────────────────────────────
  "story.button":   { en: "Explain Malaysia Labour Trends",   bm: "Terangkan Trend Buruh Malaysia" },
  "story.title":    { en: "Story Mode",    bm: "Mod Cerita"  },
  "story.previous": { en: "Previous",      bm: "Sebelumnya"  },
  "story.next":     { en: "Next",          bm: "Seterusnya"  },
  "story.done":     { en: "Done ✓",        bm: "Selesai ✓"   },
  "story.s1.title": { en: "Employment Overview",    bm: "Gambaran Keseluruhan Pekerjaan" },
  "story.s1.body":  { en: "Malaysia experienced a gradual recovery in employment following the pandemic, with job numbers steadily increasing since 2021. The labour force has grown consistently over the years — a remarkable expansion driven by economic development and population growth.",
                      bm: "Malaysia mengalami pemulihan beransur-ansur dalam sektor pekerjaan selepas pandemik, dengan jumlah pekerjaan meningkat secara berterusan sejak 2021. Tenaga kerja telah berkembang secara konsisten sepanjang tahun, satu pengembangan luar biasa yang didorong oleh pembangunan ekonomi dan pertumbuhan penduduk." },
  "story.s2.title": { en: "The COVID-19 Shock",     bm: "Kejutan COVID-19"              },
  "story.s2.body":  { en: "The pandemic caused Malaysia's unemployment rate to spike dramatically in 2020, reaching its highest level in decades. Movement control orders halted entire industries overnight, pushing hundreds of thousands out of work in a matter of months.",
                      bm: "Pandemik menyebabkan kadar pengangguran Malaysia melonjak secara mendadak pada 2020, mencapai paras tertinggi dalam beberapa dekad. Perintah kawalan pergerakan menghentikan seluruh industri dalam sekelip mata, menyebabkan ratusan ribu rakyat kehilangan pekerjaan dalam masa beberapa bulan sahaja." },
  "story.s3.title": { en: "The Recovery",           bm: "Pemulihan"                     },
  "story.s3.body":  { en: "From 2021 onwards, Malaysia's labour market staged an impressive recovery. Vaccination rollouts, economic reopening and targeted government interventions helped bring unemployment back down toward pre-pandemic levels by 2022.",
                      bm: "Bermula 2021, pasaran buruh Malaysia mencatat pemulihan yang mengagumkan. Pelancaran vaksinasi, pembukaan semula ekonomi dan campur tangan kerajaan yang disasarkan membantu menurunkan pengangguran kembali ke paras sebelum pandemik menjelang 2022." },
  "story.s4.title": { en: "Where We Are Now",       bm: "Di Mana Kita Sekarang"         },
  "story.s4.body":  { en: "Today, Malaysia's labour market shows resilience with unemployment at around 2.9% and labour force participation at 70.9%. However, challenges remain — skills mismatch affects over 11% of graduates, and regional disparities between states persist.",
                      bm: "Hari ini, pasaran buruh Malaysia menunjukkan ketahanan dengan kadar pengangguran sekitar 2.9% dan penyertaan tenaga kerja pada 70.9%. Walau bagaimanapun, cabaran masih berterusan, ketidakpadanan kemahiran menjejaskan lebih 11% graduan, dan jurang antara negeri masih wujud." },

  // ── AI Analyst ────────────────────────────────────────────────────────────
  "ai.button":    { en: "Ask AI Analyst",            bm: "Tanya Penganalisis AI"       },
  "ai.title":     { en: "AI Labour Analyst",         bm: "Penganalisis Buruh AI"       },
  "ai.subtitle":  { en: "Live DOSM data + web search",
                    bm: "Data DOSM terkini + carian web"                              },
  "ai.welcome":   { en: "Hi! I'm your Malaysia Labour Market AI Analyst. I have access to live DOSM data and can search current news to answer your questions. Ask me anything — about employment trends, sectors, states, or Malaysia's economy.",
                    bm: "Hai! Saya Penganalisis AI Pasaran Buruh Malaysia anda. Saya mempunyai akses kepada data DOSM terkini dan boleh mencari berita semasa untuk menjawab soalan anda. Tanya apa sahaja, tentang trend pekerjaan, sektor, negeri, atau ekonomi Malaysia." },
  "ai.suggested": { en: "Suggested questions:",     bm: "Soalan dicadangkan:"         },
  "ai.placeholder":{ en: "Ask anything about Malaysia's job market...",
                    bm: "Tanya apa sahaja tentang pasaran kerja Malaysia..."           },
  "ai.powered":   { en: "Powered by Gemini 2.5",    bm: "Dikuasakan oleh Gemini 2.5" },
  "ai.analysing": { en: "Analysing data + searching web...",
                    bm: "Menganalisis data dan mencari di web..."                      },
  "ai.sources":   { en: "Sources:",                 bm: "Sumber:"                     },

  // ── Trend Alerts ──────────────────────────────────────────────────────────
  "alert.warning":  { en: "Warning",  bm: "Amaran"   },
  "alert.positive": { en: "Positive", bm: "Positif"  },
  "alert.info":     { en: "Info",     bm: "Maklumat" },
  "alert.uRateRose":    { en: "Unemployment rate rose from",
                          bm: "Kadar pengangguran meningkat daripada"  },
  "alert.uRateDropped": { en: "Unemployment rate dropped from",
                          bm: "Kadar pengangguran turun daripada"      },
  "alert.rateConnector":   { en: "to",  bm: "kepada" },
  "alert.overPast3Months": { en: "over the past 3 months.",
                             bm: "sepanjang 3 bulan lepas."            },
  "alert.statesHighUnemp": { en: "state(s) have unemployment above 4%:",
                             bm: "negeri mencatat pengangguran melebihi 4%:" },
  "alert.lfprTrendingUp":  { en: "Labour force participation is trending upward at",
                             bm: "Penyertaan tenaga kerja menunjukkan trend naik pada" },
  "alert.empGrew":         { en: "Employment grew by",     bm: "Pekerjaan meningkat sebanyak" },
  "alert.empDeclined":     { en: "Employment declined by", bm: "Pekerjaan menurun sebanyak"   },
  "alert.jobsLastMonth":   { en: "jobs last month",        bm: "pekerjaan bulan lepas"        },
  "alert.lfSurpassed":     { en: "Malaysia's labour force has surpassed 17 million workers",
                             bm: "Tenaga kerja Malaysia telah melepasi 17 juta pekerja"       },

  // ── Wages by Industry ─────────────────────────────────────────────────────
  "wages.title":     { en: "Wages by Industry",        bm: "Gaji mengikut Industri"          },
  "wages.desc":      { en: "Formal sector median & mean wages",
                       bm: "Gaji median dan purata sektor formal"                             },
  "wages.tabMedian": { en: "Median Wage",              bm: "Gaji Median"                     },
  "wages.tabMean":   { en: "Mean Wage",                bm: "Gaji Purata"                     },
  "wages.tabTrend":  { en: "Trend",                    bm: "Trend"                           },
  "wages.topEarner": { en: "Highest paying",           bm: "Paling tinggi gaji"              },
  "wages.medianWage":{ en: "Median Wage",              bm: "Gaji Median"                     },
  "wages.meanWage":  { en: "Mean Wage",                bm: "Gaji Purata"                     },
  "wages.trendDesc": { en: "Median wage trend for top-paying industries",
                       bm: "Trend gaji median untuk industri bergaji tertinggi"               },
  "wages.noData":    { en: "No wage data available",   bm: "Tiada data gaji tersedia"        },

  // ── Sectors , extra ───────────────────────────────────────────────────────
  "sectors.servicesPrefix":      { en: "Services sector",       bm: "Sektor Perkhidmatan"       },
  "sectors.agriSharePrefix":     { en: "Agriculture share",     bm: "Bahagian Pertanian"        },
  "sectors.structuralChangeFrom":{ en: "Structural change from",bm: "Perubahan struktur daripada"},
  "sectors.structuralChangeTo":  { en: "to",                    bm: "kepada"                    },
  "sectors.econTransform":       { en: "Malaysia's economic transformation",
                                   bm: "Transformasi ekonomi Malaysia"                         },
  "sectors.ppNote":              { en: "pp = percentage points shift in workforce share",
                                   bm: "pp = perubahan mata peratusan dalam bahagian tenaga kerja" },

  // ── Underemployment , extra ───────────────────────────────────────────────
  "under.noRateData":      { en: "No rate data available",   bm: "Tiada data kadar tersedia"       },
  "under.trendNoData":     { en: "Trend data not available", bm: "Data trend tidak tersedia"       },
  "under.mismatchRate":    { en: "Mismatch Rate",            bm: "Kadar Ketidakpadanan"            },
  "under.skillsMismatch":  { en: "Skills Mismatch",          bm: "Ketidakpadanan Kemahiran"        },
  "under.latestQuarter":   { en: "Latest quarter",           bm: "Suku tahun terkini"             },
  "under.youthAre":        { en: "are",                      bm: "adalah"                         },
  "under.youthMoreLikely": { en: "more likely to be underemployed than workers aged 45+",
                             bm: "lebih berkemungkinan bekerja di bawah kelayakan berbanding pekerja berumur 45 tahun ke atas" },

  // ── Common ────────────────────────────────────────────────────────────────
  "common.all":     { en: "All",          bm: "Semua"        },
  "common.male":    { en: "Male",         bm: "Lelaki"       },
  "common.female":  { en: "Female",       bm: "Perempuan"    },
  "common.source":  { en: "Source",       bm: "Sumber"       },
  "common.sources": { en: "Sources",      bm: "Sumber"       },
  "common.loading": { en: "Loading...",   bm: "Memuatkan..."  },
  "common.of":      { en: "of workforce", bm: "tenaga kerja" },
  "common.share":   { en: "Share",        bm: "Bahagian"     },
  "common.export":  { en: "Export PNG",   bm: "Eksport PNG"  },
  "kpi.yoy":        { en: "YoY",          bm: "TkT"          },
};

const LanguageContext = createContext<LanguageContextType>({
  lang: "en",
  toggleLang: () => {},
  t: (key) => key,
});

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLang] = useState<Lang>(() => {
    const saved = localStorage.getItem("dashboard-lang");
    return (saved === "bm" ? "bm" : "en") as Lang;
  });

  const toggleLang = useCallback(() => {
    setLang(prev => {
      const next = prev === "en" ? "bm" : "en";
      localStorage.setItem("dashboard-lang", next);
      return next;
    });
  }, []);

  const t = useCallback((key: string) => {
    return translations[key]?.[lang] ?? key;
  }, [lang]);

  return (
    <LanguageContext.Provider value={{ lang, toggleLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);